#!/bin/bash
set -x

job_id=$CI_JOB_ID
pipeline_id=$CI_PIPELINE_ID
time="date"
source ~/.profile
gittoken=$(echo "$github_token")
commit_id=$CI_COMMIT_SHA
current_time=$(eval $time)

echo "Setting up test dependencies.."	
${utils_path}/setup_dependencies litmus-test	

bash script/utils/e2e-cr jobname:app-deploy-rwx jobphase:Waiting
bash script/utils/e2e-cr jobname:app-deploy-rwx jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id"

test_name=$(bash script/utils/generate_test_name testcase=wordpress-deployment metadata="")
echo $test_name

cd litmus

echo "Running the litmus test.."
cp apps/wordpress/deployers/run_litmus_test.yml deploy_app.yml

# Replace the storage class name
sed -i -e 's/value: openebs-nfs/value: openebs-nfs4/g' deploy_app.yml

cat deploy_app.yml

bash ../script/utils/litmus_job_runner label='app:wordpress-litmus' job=deploy_app.yml

echo "Dumping state of cluster post job run"; echo ""
cd ..
bash script/utils/dump_cluster_state;

bash script/utils/event_updater jobname:app-deploy-rwx $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

if [ "$?" != "0" ]; then
exit 1;
fi

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

## Check the test status & result from the litmus result custom resource
current_time=$(eval $time)
bash script/utils/e2e-cr jobname:app-deploy-rwx jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" test_result:$testResult

# python3 script/utils/result/result_update.py $job_id WOEM 3-functional "Deploy the application using nfs-provisioner accessmode as a readwritemany" $testResult $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi