#!/bin/bash
set -x

pod() {
# sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'git clone -b k8s-1-16 https://github.com/mayadata-io/e2e-packet.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-packet && bash script/3-functional/Jiva-Snapshot-Delete/jiva-snapshot-delete node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)

source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash script/utils/e2e-cr jobname:jiva-internal-snapshot-deletion jobphase:Waiting
bash script/utils/e2e-cr jobname:jiva-internal-snapshot-deletion jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" 

################
# LitmusBook 1 #
################

: << EOF
  --------------------------------------------------------------------------------------------------------------------     
 | specAttribute     | kind   |         default value               | test specifc value                              |
  ------------------------------------------------------------------------------------------------------------------- |
 | storage clas      | env    | openebs-jiva-standard               | openebs-jiva-default                            |
 | appNamespace      | env    | fio                                 | fio-jiva-snapshot-del                           |
  ---------------------------------------------------------------------------------------------------------------------
EOF

test_name=$(bash script/utils/generate_test_name testcase=fio-di-delete-jiva-snapshots metadata="")
echo $test_name


cd litmus
echo "Running the litmus test for Jiva internal snapshot deletion."
cp experiments/functional/snapshot_deletion/jiva/run_litmus_test.yml jiva_snapshot_delete.yml

sed -i -e 's/value: fio/value: fio-jiva-snapshot-del/g' \
-e 's/value: openebs-jiva-standard/value: openebs-jiva-default/g' jiva_snapshot_delete.yml

cat jiva_snapshot_delete.yml

bash ../script/utils/litmus_job_runner label='app:fio-di-litmus-snap-del' job=jiva_snapshot_delete.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:jiva-internal-snapshot-deletion $test_name jobid:"$job_id" pipelineid:"$pipeline_id" 

if [ "$?" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id 8QQP 3-functional "Verify if the snapshot is getting Deleted Automatically" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi