#!/bin/bash
set -x

job_id=$CI_JOB_ID
pipeline_id=$CI_PIPELINE_ID
commit_id=$CI_COMMIT_SHA

source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

echo "Setting up test dependencies.."	
${utils_path}/setup_dependencies litmus-test

bash script/utils/e2e-cr jobname:jiva-internal-snapshot-deletion jobphase:Waiting
bash script/utils/e2e-cr jobname:jiva-internal-snapshot-deletion jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" 

################
# LitmusBook 1 #
################

: << EOF
  --------------------------------------------------------------------------------------------------------------------     
 | specAttribute     | kind   |         default value               | test specifc value                              |
  ------------------------------------------------------------------------------------------------------------------- |
 | storage clas      | env    | openebs-jiva-standard               | openebs-jiva-default                            |
 | appNamespace      | env    | fio                                 | fio-jiva-snapshot-del                           |
  ---------------------------------------------------------------------------------------------------------------------
EOF

test_name=$(bash script/utils/generate_test_name testcase=fio-di-delete-jiva-snapshots metadata="")
echo $test_name


cd litmus
echo "Running the litmus test for Jiva internal snapshot deletion."
cp experiments/functional/snapshot_deletion/jiva/run_litmus_test.yml jiva_snapshot_delete.yml

sed -i -e 's/value: fio/value: fio-jiva-snapshot-del/g' \
-e 's/value: openebs-jiva-standard/value: openebs-jiva-default/g' jiva_snapshot_delete.yml

cat jiva_snapshot_delete.yml

bash ../script/utils/litmus_job_runner label='app:fio-di-litmus-snap-del' job=jiva_snapshot_delete.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:jiva-internal-snapshot-deletion $test_name jobid:"$job_id" pipelineid:"$pipeline_id" 

if [ "$?" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id 8QQP 3-functional "Verify if the snapshot is getting Deleted Automatically" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi
