#!/bin/bash
set -x

source ~/.profile
gittoken=$(echo "$github_token")

job_id=$CI_JOB_ID
pipeline_id=$CI_PIPELINE_ID
commit_id=$CI_COMMIT_SHA

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

echo "Setting up test dependencies.."	
${utils_path}/setup_dependencies litmus-test

bash script/utils/e2e-cr jobname:target-loss jobphase:Waiting
bash script/utils/e2e-cr jobname:target-loss jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id"

################
# LitmusBook 1 #
################

echo "*******Deploying Busybox Application****"

test_name=$(bash script/utils/generate_test_name testcase=busybox-provision-target-loss metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for Busybox Deployment.."

cp apps/busybox/deployers/run_litmus_test.yml busybox_target_loss.yml

sed -i -e 's/app: busybox-litmus/app: deploy-busybox-target-loss/g' \
-e 's/app=busybox-sts/app=target-loss/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: openebs-busybox/value: openebs-bb-targetloss/g' \
-e 's/value: app-busybox-ns/value: target-loss/g' busybox_target_loss.yml
cat busybox_target_loss.yml

bash ../script/utils/litmus_job_runner label='app:deploy-busybox-target-loss' job=busybox_target_loss.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:target-loss $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

if [ "$?" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 2 #
################

run_id="target-loss";test_name=$(bash script/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_target_loss.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | target-loss                                      | 
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-target-loss            |
 | appLabel          | env    | app=busybox-sts                     | app=target-loss                                  | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: target-loss/g' \
-e 's/app=busybox-sts/app=target-loss/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-target-loss/g' busybox_loadgen_target_loss.yml

cat busybox_loadgen_target_loss.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_target_loss.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../script/utils/litmus_job_runner label='liveness:busybox-liveness-target-loss' job=busybox_loadgen_target_loss.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash script/utils/dump_cluster_state;
# Update the e2e event for the job.
bash script/utils/event_updater jobname:target-loss $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

if [ "$?" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 3 #
################

echo "*******Performing Network loss on target**********"

test_name=$(bash script/utils/generate_test_name testcase=openebs-target-network-loss metadata="")
echo $test_name

cd litmus
cp experiments/chaos/openebs_target_network_loss/run_litmus_test.yml run_targetloss_test.yml

sed -i -e 's/value: percona-mysql-claim/value: openebs-bb-targetloss/g' \
-e 's/value: '\''name=percona'\''/value: '\''app=target-loss'\''/g' \
-e 's/value: '\''enable'\''/value: '\'""\''/g' \
-e 's/value: app-percona-ns/value: target-loss/g' run_targetloss_test.yml

echo "Running the litmus test for Busybox Deployment Scaleup.."
cat run_targetloss_test.yml

bash ../script/utils/litmus_job_runner label='name:openebs-target-network-loss' job=run_targetloss_test.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:target-loss $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

if [ "$?" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 4 #
################

run_id="deprovision-target-loss";test_name=$(bash script/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_deprovision_target_loss.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | target-loss                                      | 
 | appLabel          | env    | app=busybox-sts                     | app=target-loss                                  |
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-deprovision-target-loss|
 | action            | env    | provision                           | deprovision                                      | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: target-loss/g' \
-e 's/app=busybox-sts/app=target-loss/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/generateName: litmus-busybox-liveness/generateName: busybox-liveness-dep-target-loss/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-deprovision-target-loss/g' busybox_loadgen_deprovision_target_loss.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_target_loss.yml

cat busybox_loadgen_deprovision_target_loss.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../script/utils/litmus_job_runner label='liveness:busybox-liveness-deprovision-target-loss' job=busybox_loadgen_deprovision_target_loss.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:target-loss $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-packet repository.
if [ "$rc_val" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 5 #
################

echo "********Deprovisioning Busybox Application*******"

test_name=$(bash script/utils/generate_test_name testcase=busybox-deprovision-target-loss metadata="")
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_target_loss.yml

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-target-loss/g' \
-e 's/app: busybox-litmus/app: busybox-deprovision-target-loss/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/app=busybox-sts/app=target-loss/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-busybox/value: openebs-bb-targetloss/g' \
-e 's/value: app-busybox-ns/value: target-loss/g' \
-e 's/value: provision/value: deprovision/g' deprovision_target_loss.yml

echo "Running the litmus test for Busybox Deployment.."
cat deprovision_target_loss.yml

bash ../script/utils/litmus_job_runner label='app:busybox-deprovision-target-loss' job=deprovision_target_loss.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:target-loss $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

rc_val=$(echo $?)

# testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

if [ "$rc_val" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

current_time=$(eval $time)
bash script/utils/e2e-cr jobname:target-loss jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" test_result:Pass
# python3 script/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
