#!/bin/bash
set -x

source ~/.profile
gittoken=$(echo "$github_token")

job_id=$CI_JOB_ID
pipeline_id=$CI_PIPELINE_ID
commit_id=$CI_COMMIT_SHA
releaseTag=$RELEASE_TAG

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

echo "Setting up test dependencies.."	
${utils_path}/setup_dependencies litmus-test

bash script/utils/e2e-cr jobname:target-network-loss jobphase:Waiting
bash script/utils/e2e-cr jobname:target-network-loss jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"

################
# LitmusBook 1 #
################

echo "*******Deploying Percona Application****"

test_name=$(bash script/utils/generate_test_name testcase=percona-deployment metadata="")
echo $test_name

git clone https://github.com/mayadata-io/litmus.git
cd litmus
echo "Running the litmus test for Percona Deployment.."

cp apps/percona/deployers/run_litmus_test.yml percona_target_network_loss.yml

sed -i -e 's/app: percona-deployment/app: deploy-percona-target-nw-loss/g' \
-e 's/generateName: litmus-percona-/generateName: litmus-percona-nw-loss-/g' \
-e 's/value: openebs-standard/value: openebs-cstor-disk/g' \
-e 's/value: app-percona-ns/value: percona-target-nw-loss/g' percona_target_network_loss.yml
cat percona_target_network_loss.yml

bash ../script/utils/litmus_job_runner label='app:deploy-percona-target-nw-loss' job=percona_target_network_loss.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:target-network-loss $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

if [ "$?" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 2 #
################

run_id="target-nw-loss";test_name=$(bash script/utils/generate_test_name testcase=percona-loadgen metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/percona/workload/run_litmus_test.yml percona_loadgen_target_nw_loss.yml

# Update the environmental variables in litmus job spec.

sed -i -e 's/value: app-percona-ns/value: percona-target-nw-loss/g' \
-e 's/generateName: percona-loadgen-/generateName: percona-loadgen-nw-loss-/g' \
-e 's/loadgen: percona-loadjob/loadgen: percona-loadjob-nw-loss/g' percona_loadgen_target_nw_loss.yml

cat percona_loadgen_target_nw_loss.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_loadgen_target_nw_loss.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../script/utils/litmus_job_runner label='loadgen:percona-loadjob-nw-loss' job=percona_loadgen_target_nw_loss.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash script/utils/dump_cluster_state;
# Update the e2e event for the job.
bash script/utils/event_updater jobname:target-network-loss $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

if [ "$?" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 3 #
################

echo "*******Performing Network loss on target**********"

test_name=$(bash script/utils/generate_test_name testcase=openebs-target-network-loss metadata="")
echo $test_name

cd litmus
cp experiments/chaos/openebs_target_network_loss/run_litmus_test.yml run_target_nw_loss_test.yml

sed -i -e 's/value: app-percona-ns/value: percona-target-nw-loss/g' run_target_nw_loss_test.yml

## Replace the value of DATA_PERSISTENCE with application name in litmus experiment.
sed -i '/name: DATA_PERSISTENCE/{n;s/.*/            value: mysql/}' run_target_nw_loss_test.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    dbuser: root \
    dbpassword: k8sDem0 \
    dbname: targetnwlosstest
' run_target_nw_loss_test.yml

cat run_target_nw_loss_test.yml

bash ../script/utils/litmus_job_runner label='name:openebs-target-network-loss' job=run_target_nw_loss_test.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:target-network-loss $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

if [ "$?" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi


################
# LitmusBook 4 #
################

echo "********Deprovisioning Percona Application*******"

run_id="deprovision";test_name=$(bash script/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name

cd litmus
cp apps/percona/deployers/run_litmus_test.yml percona_deprovision_target_network_loss.yml

sed -i -e 's/app: percona-deployment/app: deprovision-percona-target-nw-loss/g' \
-e 's/generateName: litmus-percona-/generateName: litmus-percona-deprovision-nw-loss-/g' \
-e 's/value: openebs-standard/value: openebs-cstor-disk/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/value: app-percona-ns/value: percona-target-nw-loss/g' percona_deprovision_target_network_loss.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_deprovision_target_network_loss.yml           

echo "Running the litmus test for percona Deprovision.."
cat percona_deprovision_target_network_loss.yml

bash ../script/utils/litmus_job_runner label='app:deprovision-percona-target-nw-loss' job=percona_deprovision_target_network_loss.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:target-network-loss $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

rc_val=$(echo $?)

# testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

if [ "$rc_val" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

current_time=$(eval $time)
bash script/utils/e2e-cr jobname:target-network-loss jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Pass
# python3 script/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
