#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

## https://github.com/openebs/litmus/blob/master/apps/percona/chaos/cstor_pool_scale/test_vars.yml
test_name=$(${utils_path}/generate_test_name testcase=cstor-pool-scale metadata="")

###################
## DEPENDENCIES  ##
###################

${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 

git clone https://github.com/openebs/litmus.git
cd litmus

############################
## LITMUS PRECONDITIONING ##
############################

cp apps/percona/chaos/cstor_pool_scale/run_litmus_test.yml run_test.yml
sed -i 's/value: app-percona-ns/value: percona-cstor/g' run_test.yml

#################   
## RUNNER MAIN ##
#################

## TODO: Keep testnames & label names similar & keep keys consistent for a type of test
echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='name:cstor-pool-scale' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}