#!/bin/bash
set -x

job_id=$CI_JOB_ID
pipeline_id=$CI_PIPELINE_ID
commit_id=$CI_COMMIT_SHA
releaseTag=$RELEASE_TAG
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

echo "Setting up test dependencies.."
${utils_path}/setup_dependencies infra-setup

bash script/utils/e2e-cr jobname:csi-cstor-snapshot jobphase:Waiting
bash script/utils/e2e-cr jobname:csi-cstor-clone jobphase:Waiting
bash script/utils/e2e-cr jobname:csi-cstor-snapshot jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"

################
# LitmusBook 1 #
################

echo "*******Deploying Busybox Application****"

test_name=$(bash script/utils/generate_test_name testcase=busybox-provision-cstor-snap-clone metadata="")
echo $test_name
git clone https://github.com/mayadata-io/litmus.git
cd litmus
echo "Running the litmus test for Busybox Deployment.."

cp apps/busybox/deployers/run_litmus_test.yml busybox_snap_clone.yml

sed -i -e 's/app: busybox-litmus/app: deploy-busybox-snap-clone/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-csi/g' \
-e 's/value: openebs-busybox/value: csi-vol/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: app-busybox-ns/value: cstor-snap-clone/g' busybox_snap_clone.yml
cat busybox_snap_clone.yml

bash ../script/utils/litmus_job_runner label='app:deploy-busybox-snap-clone' job=busybox_snap_clone.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:csi-cstor-snapshot $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

################
# LitmusBook 2 #
################

echo "*******Performing snapshot litmus test**********"

test_name=$(bash script/utils/generate_test_name testcase=cstor-csi-snapshot metadata="")
echo $test_name

cd litmus
cp experiments/functional/cstor-csi/csi-snapshot/run_litmus_test.yml run_snapshot_test.yml

## Replace the value of DATA_PERSISTENCE with application name in litmus experiment. 
sed -i -e '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: cstor-snap-clone/}' \
-e '/name: APP_PVC/{n;s/.*/            value: csi-vol/}' run_snapshot_test.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k\
    blockcount: 1024\
    testfile: csisnapclonetest
' run_snapshot_test.yml

echo "Running the litmus test for creation of snapshot.."
cat run_snapshot_test.yml

bash ../script/utils/litmus_job_runner label='name:cstor-csi-snapshot' job=run_snapshot_test.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:csi-cstor-snapshot $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the litmus result custom resource
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash script/utils/e2e-cr jobname:csi-cstor-snapshot jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Pass

if [ "$rc_val" != "0" ]; then
exit 1;
fi