#!/bin/bash
set -x

source ~/.profile
gittoken=$(echo "$github_token")

job_id=$CI_JOB_ID
pipeline_id=$CI_PIPELINE_ID
commit_id=$CI_COMMIT_SHA

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

echo "Setting up test dependencies.."	
${utils_path}/setup_dependencies litmus-test

bash script/utils/e2e-cr jobname:data-integrity-jiva jobphase:Waiting init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id"
bash script/utils/e2e-cr jobname:data-integrity-jiva jobphase:Running

################
# LitmusBook 1 #
################

run_id="jiva";test_name=$(bash script/utils/generate_test_name testcase=fio-data-integrity metadata=${run_id})
echo $test_name
cd litmus

cp experiments/functional/fio/data-integrity/run_litmus_test.yml data_integrity_test_jiva.yml

: << EOF
  --------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind     | default busybox value               | test specifc value                      |
  --------------------------------------------------------------------------------------------------------------|
 | imagePullPolicy   | image    | Always                              | IfNotPresent                            |
 | LitmusjobLabel    | label    | app:fio-di-litmus                   | app:fio-di-litmus-jiva                  |
 | storage class     | env      | openebs-standard                    | openebs-jiva-default                    |
 | appNamespace      | env      | fio                                 | fio-jiva                                | 
  --------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/value: openebs-standard/value: openebs-jiva-default/g' \
-e 's/app: fio-di-litmus/app: fio-di-litmus-jiva/g' \
-e 's/value: fio/value: fio-jiva/g' data_integrity_test_jiva.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' data_integrity_test_jiva.yml

cat data_integrity_test_jiva.yml

bash ../script/utils/litmus_job_runner label='app:fio-di-litmus-jiva' job=data_integrity_test_jiva.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:data-integrity-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

rc_val=$(echo $?)

testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

if [ "$rc_val" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id UH9A 3-functional "Ensure the data integrity in openebs volume using fio" $testResult $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

current_time=$(eval $time)
bash script/utils/e2e-cr jobname:data-integrity-jiva jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" test_result:$testResult

# python3 script/utils/result/result_update.py $job_id UH9A 3-functional "Ensure the data integrity in openebs volume using fio" $testResult $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi

