#!/bin/bash
set -x

pod() {
echo $CI_JOB_ID
###clone e2e-packet-repo
echo "cloning e2e-packet repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'git clone -b k8s-1-16 https://github.com/mayadata-io/e2e-packet.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-packet && bash script/3-functional/Jiva-Data-Integrity/jiva-data-integrity node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {
source ~/.profile
gittoken=$(echo "$github_token")
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash script/utils/e2e-cr jobname:data-integrity-jiva jobphase:Waiting init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id"
bash script/utils/e2e-cr jobname:data-integrity-jiva jobphase:Running

################
# LitmusBook 1 #
################

run_id="jiva";test_name=$(bash script/utils/generate_test_name testcase=fio-data-integrity metadata=${run_id})
echo $test_name
cd litmus

cp experiments/functional/fio/data-integrity/run_litmus_test.yml data_integrity_test_jiva.yml

: << EOF
  --------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind     | default busybox value               | test specifc value                      |
  --------------------------------------------------------------------------------------------------------------|
 | imagePullPolicy   | image    | Always                              | IfNotPresent                            |
 | LitmusjobLabel    | label    | app:fio-di-litmus                   | app:fio-di-litmus-jiva                  |
 | storage class     | env      | openebs-standard                    | openebs-jiva-default                    |
 | appNamespace      | env      | fio                                 | fio-jiva                                | 
  --------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/value: openebs-standard/value: openebs-jiva-default/g' \
-e 's/app: fio-di-litmus/app: fio-di-litmus-jiva/g' \
-e 's/value: fio/value: fio-jiva/g' data_integrity_test_jiva.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' data_integrity_test_jiva.yml

cat data_integrity_test_jiva.yml

bash ../script/utils/litmus_job_runner label='app:fio-di-litmus-jiva' job=data_integrity_test_jiva.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:data-integrity-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

rc_val=$(echo $?)

testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

if [ "$rc_val" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id UH9A 3-functional "Ensure the data integrity in openebs volume using fio" $testResult $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

current_time=$(eval $time)
bash script/utils/e2e-cr jobname:data-integrity-jiva jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" test_result:$testResult

# python3 script/utils/result/result_update.py $job_id UH9A 3-functional "Ensure the data integrity in openebs volume using fio" $testResult $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi
