#!/bin/bash
set -x 

derive_cluster_details_infra()
{
 
 ## Get kubeconfig file into infra-setup gitlab runner pod
 mkdir ~/.kube openebs-packet openebs-packet/.kube 
 cp -r cluster/.kube/. ~/.kube/
 cp -r cluster/.kube/. openebs-packet/.kube/
}
 
setup_cluster_config_test()
{
 mkdir ~/.kube
 cp -r openebs-packet/.kube/. ~/.kube/
}

if [[ $1 == "infra-setup" ]]; then
 derive_cluster_details_infra;
elif [[ $1 == "litmus-test" ]]; then
 setup_cluster_config_test;
else echo "invalid job type"; exit 1
fi 
