#!/bin/bash
set -e

echo "creating packet-cluster"
mkdir ~/.kube   /openebs/e2e-packet/cluster /openebs/e2e-packet/cluster/ssh /openebs/e2e-packet/cluster/.kube
export PACKET_API_TOKEN=$packet_api_token
git clone https://github.com/chandankumar4/litmus.git
cd litmus/k8s/packet/k8s-installer && git checkout packet-cloud
echo "--------------- creating packet cluster --------------------"
ansible-playbook create_packet_cluster.yml --extra-vars "k8s_version=1.10.0-00" -v
kubectl get nodes
kubectl get pods --all-namespaces
kubectl apply -f https://raw.githubusercontent.com/openebs/litmus/master/hack/rbac.yaml
cp -r /tmp/packet/. /openebs/e2e-packet/cluster/
cat ~/.kube/config > /openebs/e2e-packet/cluster/.kube/admin.conf
cp -r ~/.kube/. /openebs/e2e-packet/cluster/.kube/
cp -r ~/.ssh/. /openebs/e2e-packet/cluster/ssh
kubectl create configmap kubeconfig --from-file=/openebs/e2e-packet/cluster/.kube/admin.conf -n litmus
kubectl get pods --all-namespaces
kubectl get nodes
