#!/bin/bash

set -e

echo "Packet-Cleanup"
mkdir ~/.kube ~/.ssh /tmp/packet
cp -r .kube/. ~/.kube/
cp -r cluster/ssh/. ~/.ssh/ && eval `ssh-agent -s` && ssh-add
cp e2e-packet/cluster/device_id /tmp/packet/
export PACKET_API_TOKEN=$packet_api_token
mkdir cluster && cd cluster
git clone https://github.com/chandankumar4/litmus.git
cd litmus/k8s/packet/k8s-installer && git checkout packet
echo "--------------- deleting packet cluster --------------------"
ansible-playbook delete_packet_cluster.yml -vvv
