#!/bin/bash

set -e

path=$(pwd)
echo "Packet-Cleanup"
mkdir ~/.kube ~/.ssh /tmp/packet
cp -r $path/cluster/.kube/. ~/.kube/
cp -r $path/cluster/ssh/. ~/.ssh/ && eval `ssh-agent -s` && ssh-add
cp $path/cluster/device_id /tmp/packet/
export PACKET_API_TOKEN=$packet_api_token
git clone https://github.com/openebs/litmus.git
cd litmus/k8s/packet/k8s-installer
echo "--------------- deleting packet cluster --------------------"
ansible-playbook delete_packet_cluster.yml -vv

