#!/bin/bash
set -e

echo "Deploying statefulapps"

mkdir ~/.kube packet-percona packet-percona/.kube
cp -r openebs-packet/.kube/. ~/.kube/
cp -r openebs-packet/.kube/. packet-percona/.kube/

# echo "attaching disks"

git clone https://github.com/atulabhi/litmus.git

cd litmus

git checkout v0.7-RC1

#cd k8s/aws/ebs-volumes/

#cluster=$(cat /tmp/aws/cluster_name.csv | cut -d: -f2)
#ansible-playbook create-ebs-volume.yml -vv --extra-vars "cluster_name=nodes.k8s-$cluster.k8s.local"

wget https://raw.githubusercontent.com/atulabhi/litmus/v0.7-RC1/providers/openebs/installers/storageclass/0.7/litmusbook/storageclass_setup.yaml


#kubectl apply -f  storageclass_setup.yaml


kubectl apply -f apps/percona/deployers/deploy_percona_litmus.yaml

litmus_pod=$(kubectl get pod -a -n litmus --no-headers -o custom-columns=:metadata.name | grep litmus-percona-jiva)
status_cmd='kubectl logs $litmus_pod -n litmus -c ansibletest'

sleep 120
while [[ $(kubectl get pod $litmus_pod --no-headers -n litmus -o custom-columns=:status.phase) =~ 'Running' ]]
do
   echo "Still Running sir..."
   sleep 1
done
if [[ ! $(eval $status_cmd) =~ 'FAILED!' ]]; then
   TestStatus='Pass'
else
  TestStatus='Fail'
fi
echo $TestStatus

echo "========================================================================="

eval $status_cmd

kubectl get po -n litmus

kubectl get sc

#kubectl get sp
