#!/bin/bash
set -x

source ~/.profile
gittoken=$(echo "$github_token")

job_id=$CI_JOB_ID
pipeline_id=$CI_PIPELINE_ID
commit_id=$CI_COMMIT_SHA

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

echo "Setting up test dependencies.."	
${utils_path}/setup_dependencies litmus-test

bash script/utils/e2e-cr jobname:target-kill jobphase:Waiting init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id"
bash script/utils/e2e-cr jobname:target-kill jobphase:Running init_time:"$current_time"

################
# LitmusBook 1 #
################

echo "*******Deploying Busybox Application****"

test_name=$(bash script/utils/generate_test_name testcase=busybox-provision-target-kill metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for Busybox Deployment.."

cp apps/busybox/deployers/run_litmus_test.yml busybox_target_kill.yml

sed -i -e 's/app: busybox-litmus/app: deploy-busybox-target-kill/g' \
-e 's/app=busybox-sts/app=target-kill/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: openebs-busybox/value: openebs-bb-targetkill/g' \
-e 's/value: app-busybox-ns/value: target-kill/g' busybox_target_kill.yml
cat busybox_target_kill.yml

bash ../script/utils/litmus_job_runner label='app:deploy-busybox-target-kill' job=busybox_target_kill.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:target-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

if [ "$?" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id VZPY 4-chaos "Induce failure on cstor-target pod and check if it gets scheduled immediately and the application is available" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 2 #
################

run_id="target-kill";test_name=$(bash script/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_target_kill.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | target-kill                                      | 
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-targetkill            |
 | appLabel          | env    | app=busybox-sts                     | app=target-kill                                     | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: target-kill/g' \
-e 's/app=busybox-sts/app=target-kill/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-targetkill/g' busybox_loadgen_target_kill.yml

cat busybox_loadgen_target_kill.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_target_kill.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../script/utils/litmus_job_runner label='liveness:busybox-liveness-targetkill' job=busybox_loadgen_target_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash script/utils/dump_cluster_state;
# Update the e2e event for the job.
bash script/utils/event_updater jobname:target-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

if [ "$?" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id VZPY 4-chaos "Induce failure on cstor-target pod and check if it gets scheduled immediately and the application is available" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 3 #
################

# Performing target failure

run_id="delete";test_name=$(bash script/utils/generate_test_name testcase=openebs-target-failure metadata=${run_id})
echo $test_name

cd litmus
cp experiments/chaos/openebs_target_failure/run_litmus_test.yml run_target_kill_test.yml

sed -i -e 's/value: percona-mysql-claim/value: openebs-bb-targetkill/g' \
-e 's/value: '\''name=percona'\''/value: '\''app=target-kill'\''/g' \
-e 's/target-zrepl-kill/target-delete/g' \
-e 's/value: app-percona-ns/value: target-kill/g' run_target_kill_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_target_kill_test.yml

## Replace the value of DATA_PERSISTENCE with application name in litmus experiment. 
sed -i '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' run_target_kill_test.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k\
    blockcount: 1024\
    testfile: targetkilltest
' run_target_kill_test.yml

echo "Running the litmus test for Busybox Deployment Scaleup.."
cat run_target_kill_test.yml

bash ../script/utils/litmus_job_runner label='name:openebs-target-failure' job=run_target_kill_test.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:target-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

if [ "$?" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id VZPY 4-chaos "Induce failure on cstor-target pod and check if it gets scheduled immediately and the application is available" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 4 #
################

run_id="deprovision-target-kill";test_name=$(bash script/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_deprovision_target_kill.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | target-kill                                      | 
 | appLabel          | env    | app=busybox-sts                     | app=target-kill                                  |
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-deprovision-targetkill|
 | action            | env    | provision                           | deprovision                                      | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: target-kill/g' \
-e 's/app=busybox-sts/app=target-kill/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/generateName: litmus-busybox-liveness/generateName: busybox-liveness-dep-target-kill/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-deprovision-target-kill/g' busybox_loadgen_deprovision_target_kill.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_target_kill.yml

cat busybox_loadgen_deprovision_target_kill.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../script/utils/litmus_job_runner label='liveness:busybox-liveness-deprovision-targetkill' job=busybox_loadgen_deprovision_target_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:target-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-packet repository.
if [ "$rc_val" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id VZPY 4-chaos "Induce failure on cstor-target pod and check if it gets scheduled immediately and the application is available" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 5 #
################

echo "********Deprovisioning Busybox Application*******"

test_name=$(bash script/utils/generate_test_name testcase=busybox-deprovision-target-kill metadata="")
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_target_kill.yml

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-target-kill/g' \
-e 's/app: busybox-litmus/app: busybox-deprovision-target-kill/g' \
-e 's/app=busybox-sts/app=target-kill/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: openebs-busybox/value: openebs-bb-targetkill/g' \
-e 's/value: app-busybox-ns/value: target-kill/g' \
-e 's/value: provision/value: deprovision/g' deprovision_target_kill.yml

echo "Running the litmus test for Busybox Deployment.."
cat deprovision_target_kill.yml

bash ../script/utils/litmus_job_runner label='app:busybox-deprovision-target-kill' job=deprovision_target_kill.yml
cd ..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:target-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

rc_val=$(echo $?)

# testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

if [ "$rc_val" != "0" ]; then
# python3 script/utils/result/result_update.py $job_id VZPY 4-chaos "Induce failure on cstor-target pod and check if it gets scheduled immediately and the application is available" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

current_time=$(eval $time)
bash script/utils/e2e-cr jobname:target-kill jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" test_result:Pass
# python3 script/utils/result/result_update.py $job_id VZPY 4-chaos "Induce failure on cstor-target pod and check if it gets scheduled immediately and the application is available" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
