#!/bin/bash
set -x

job_id=$CI_JOB_ID
pipeline_id=$CI_PIPELINE_ID
commit_id=$CI_COMMIT_SHA

source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

echo "Setting up test dependencies.."	
${utils_path}/setup_dependencies litmus-test

bash script/utils/e2e-cr jobname:volume-replica-distribution jobphase:Waiting
bash script/utils/e2e-cr jobname:volume-replica-distribution jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" 

test_name=$(bash script/utils/generate_test_name testcase=replica-distribution metadata="")
echo $test_name

echo "*******Deploying Application and Check the statefulset storage volume distributed************"
cd litmus
: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | imagePullPolicy   | image  | Always                              | IfNotPresent                                     |
 | Litmus job label  | label  | app:  busybox-statefulset-litmus    | app: busybox-vol-distribute                      |
 | storage class     | env    | openebs-cstor-sparse                | openebs-cstor-disk                               |
 | appLabel          | env    | app=busybox-sts                     | app=busybox                                      | 
 | appNamespace      | env    | app-busybox-ns                      | busybox                                          | 
  ----------------------------------------------------------------------------------------------------------------------
EOF
echo "Running the litmus test.."
sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' experiments/functional/sts-volume-distribution/run_litmus_test.yml
run_test=experiments/functional/sts-volume-distribution/run_litmus_test.yml
sed -i -e 's/app: busybox-statefulset-litmus/app: busybox-vol-distribute/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: 'app=busybox-sts'/value: 'app=busybox'/g' \
-e 's/value: app-busybox-ns/value: busybox/g' $run_test
cat $run_test

bash ../script/utils/litmus_job_runner label='app:busybox-vol-distribute' job=$run_test

echo "Dumping state of cluster post job run"; echo ""
cd ..
bash script/utils/dump_cluster_state;

bash script/utils/event_updater jobname:volume-replica-distribution $test_name jobid:"$job_id" pipelineid:"$pipeline_id" 

if [ "$?" != "0" ]; then
exit 1;
fi

#################
## GET RESULT  ##
#################
rc_val=$(echo $?)
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
# python3 script/utils/result/result_update.py $test_case_id 4ZWU 3-functional "Check if the storage volume replicas are distributed across the storage pools in case of statefulset deployment" $testResult $pipeline_id "$current_time" $commit_id $gittoken

## Check the test status & result from the litmus result custom resource
current_time=$(eval $time)
bash script/utils/e2e-cr jobname:volume-replica-distribution jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id"  test_result:Pass

# python3 script/utils/result/result_update.py $job_id 4ZWU 3-functional "Check if the storage volume replicas are distributed across the storage pools in case of statefulset deployment" $testResult $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
