#!/bin/bash
set -x

#################
## ENVIRONMENT ##
#################

## https://github.com/openebs/litmus/blob/master/apps/percona/functional/snapshot-rebuild/test_vars.yml
test_name=$(${utils_path}/generate_test_name testcase=snap-rebuild-multiple-rep metadata="")

###################
## DEPENDENCIES  ##
###################

${utils_path}/setup_dependencies litmus-test

## Clone the litmus repo, navigate to litmus root 

git clone https://github.com/openebs/litmus.git
cd litmus

############################
## LITMUS PRECONDITIONING ##
############################

cp apps/percona/functional/snapshot_rebuild/snap_rebuild_multiple_rep/run_litmus_test.yml run_test.yml

#################
## RUNNER MAIN ##
#################

## TODO: Keep testnames & label names similar & keep keys consistent for a type of test
echo "Running the litmus test.."
${utils_path}/litmus_job_runner label='app:k8s-snap-multiple-rep-rebuild' job=run_test.yml
${utils_path}/task_delimiter;

echo "Dumping state of cluster post job run"; echo ""
${utils_path}/dump_cluster_state;
${utils_path}/task_delimiter;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource
${utils_path}/get_litmus_result ${test_name}